spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name?currentSchema=public
    username: your_username_here
    password: your_password_here
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 465
    username: your_email_here
    password: your_password_here
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
